export const fileConstants = {
    GETBYNAME_REQUEST: 'FILE_GETBYNAME_REQUEST',
    GETBYNAME_SUCCESS: 'FILES_GETBYNAME_SUCCESS',
    GETBYNAME_FAILURE: 'FILES_GETBYNAME_FAILURE',

    GETALL_REQUEST: 'FILES_GETALL_REQUEST',
    GETALL_SUCCESS: 'FILES_GETALL_SUCCESS',
    GETALL_FAILURE: 'FILES_GETALL_FAILURE',
}